// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLs88rkf60K_EjRlBFNvZ5Na2fqO6Dkw0',
    appId: '1:749063011762:web:a4a42a78cd4c5d353db8ab',
    messagingSenderId: '749063011762',
    projectId: 'charge-mate-iue',
    authDomain: 'charge-mate-iue.firebaseapp.com',
    storageBucket: 'charge-mate-iue.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBJ3bwnWwIbV8scXdj9x9DuNijyWwDPao',
    appId: '1:749063011762:android:413850f8a7f97e673db8ab',
    messagingSenderId: '749063011762',
    projectId: 'charge-mate-iue',
    storageBucket: 'charge-mate-iue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LPJhQhFIie93-DbxmmcRE_14_GGr4oI',
    appId: '1:749063011762:ios:b61680e68e8acd473db8ab',
    messagingSenderId: '749063011762',
    projectId: 'charge-mate-iue',
    storageBucket: 'charge-mate-iue.appspot.com',
    iosBundleId: 'com.example.chargeMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9LPJhQhFIie93-DbxmmcRE_14_GGr4oI',
    appId: '1:749063011762:ios:b43c1147af394fb13db8ab',
    messagingSenderId: '749063011762',
    projectId: 'charge-mate-iue',
    storageBucket: 'charge-mate-iue.appspot.com',
    iosBundleId: 'com.example.chargeMate.RunnerTests',
  );
}
